INSERT INTO `notes`.`credential` (`user_id`,`user_name`,`email`,`password`) VALUES ('9a68fb20-9180-4137-b8c3-a12f923f995a','dev.yonas','dev.albertusyonas@gmail.com','177c7294cd4272a57a7f4fcb04a2b8e0');
INSERT INTO `notes`.`note` (`note_id`,`user_id`,`note_title`,`note_description`) VALUES
('3f7596be-6cc5-45d9-864a-e8366c11e4e7','9a68fb20-9180-4137-b8c3-a12f923f995a','Note 1','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sollicitudin at tortor vitae placerat. Quisque pulvinar fermentum pulvinar. Suspendisse bibendum ultricies sapien vel egestas. Sed laoreet consectetur augue, et facilisis risus malesuada eget. Etiam tempor nisl id orci elementum, non aliquet magna volutpat.');
INSERT INTO `notes`.`note` (`note_id`,`user_id`,`note_title`,`note_description`) VALUES
('41a4e932-3f67-4aa6-a68d-869fd4901497','9a68fb20-9180-4137-b8c3-a12f923f995a','Note 2','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sollicitudin at tortor vitae placerat. Quisque pulvinar fermentum pulvinar. Suspendisse bibendum ultricies sapien vel egestas. Sed laoreet consectetur augue, et facilisis risus malesuada eget. Etiam tempor nisl id orci elementum, non aliquet magna volutpat.');
INSERT INTO `notes`.`note` (`note_id`,`user_id`,`note_title`,`note_description`) VALUES
('5baa24c1-63ef-4a10-b0b1-9a4894a18740','9a68fb20-9180-4137-b8c3-a12f923f995a','Note 3','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sollicitudin at tortor vitae placerat. Quisque pulvinar fermentum pulvinar. Suspendisse bibendum ultricies sapien vel egestas. Sed laoreet consectetur augue, et facilisis risus malesuada eget. Etiam tempor nisl id orci elementum, non aliquet magna volutpat.');
INSERT INTO `notes`.`note` (`note_id`,`user_id`,`note_title`,`note_description`) VALUES
('a5515ad7-e6fa-445e-82fe-9bd9426f3ab0','9a68fb20-9180-4137-b8c3-a12f923f995a','Note 4','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sollicitudin at tortor vitae placerat. Quisque pulvinar fermentum pulvinar. Suspendisse bibendum ultricies sapien vel egestas. Sed laoreet consectetur augue, et facilisis risus malesuada eget. Etiam tempor nisl id orci elementum, non aliquet magna volutpat.');
INSERT INTO `notes`.`note` (`note_id`,`user_id`,`note_title`,`note_description`) VALUES
('feadc635-4270-446e-b848-8a2ba23ecfc5','9a68fb20-9180-4137-b8c3-a12f923f995a','Note 4','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sollicitudin at tortor vitae placerat. Quisque pulvinar fermentum pulvinar. Suspendisse bibendum ultricies sapien vel egestas. Sed laoreet consectetur augue, et facilisis risus malesuada eget. Etiam tempor nisl id orci elementum, non aliquet magna volutpat.');